require 'cosmos'
require 'cosmos/script'

#based on hardline_tlm.rb in bct tool folder and Macro 17 definition for radio beacon
#sends FSW tlm to hardline for 1 minute at a rate of 1 Hz (60 packets total)
cmd('UUT RADIO_DOWNLINK with RADIO_TYPE HARDLINE, DURATION 1, RT_SRC1 FSW, RT_SRC2 NONE, RT_SRC3 NONE, RT_SRC4 NONE, RT_PERIOD 1, PB_SRC1 NONE, PB_DECIMATION1 1, PB_END1 LAST_COMPLETE, PB_COUNT1 0, PB_SRC2 NONE, PB_DECIMATION2 1, PB_END2 LAST_COMPLETE, PB_COUNT2 0, PB_SRC3 NONE, PB_DECIMATION3 1, PB_END3 LAST_COMPLETE, PB_COUNT3 0, PB_SRC4 NONE, PB_DECIMATION4 1, PB_END4 LAST_COMPLETE, PB_COUNT4 0, PB_SRC5 NONE, PB_DECIMATION5 1, PB_END5 LAST_COMPLETE, PB_COUNT5 0, PB_SRC6 NONE, PB_DECIMATION6 1, PB_END6 LAST_COMPLETE, PB_COUNT6 0')