cmd("UUT SET_LOAD_SWITCH with SWITCH_NUM IO22_V3_EN, STATUS ON")
cmd("UUT SET_LOAD_SWITCH with SWITCH_NUM IO4_PAYLOAD, STATUS ON")
cmd("UUT SET_LOAD_SWITCH with SWITCH_NUM IO27_PAYLOAD_ENABLE, STATUS ON")