#CLICK Payload Command & Telemetry APIDs:
#Reference: https://docs.google.com/spreadsheets/d/1ITNdvtceonKRpWd4pGuhg9Do2ZygTLGonbsYKwVzycM/edit#gid=1522568728

#Ground Command APIDs
CMD_PL_REBOOT = 0x01
CMD_PL_ENABLE_TIME = 0xC2
CMD_PL_DISABLE_TIME = 0xA4
CMD_PL_EXEC_FILE = 0x67
CMD_PL_LIST_FILE = 0xFE
CMD_PL_REQUEST_FILE = 0xAB
CMD_PL_UPLOAD_FILE_TOSTAGING = 0xCD
CMD_PL_SET_PAT_MODE = 0xB3
CMD_PL_SINGLE_CAPTURE = 0xF1
CMD_PL_CALIB_LASER_TEST = 0x4C 
CMD_PL_FSM_TEST = 0x28
CMD_PL_RUN_CALIBRATION = 0x32
CMD_PL_SET_FPGA = 0x54
CMD_PL_GET_FPGA = 0x0E
CMD_PL_SET_HK = 0x97
CMD_PL_ECHO = 0x3D
CMD_PL_NOOP = 0x5B
CMD_PL_DWNLINK_MODE = 0xE0
CMD_PL_DEBUG_MODE = 0xD0

#Telemetry APIDs
TLM_DL_FILE = 0x387 #TBR
TLM_HK_CPU = 0x312 #TBR
TLM_HK_PAT = 0x313 #TBR
TLM_HK_FPGA_MAP = 0x314 #TBR
TLM_ECHO = 0x3FF 
TLM_LIST_FILE = 0x3E0 
TLM_GET_FPGA = 0x3C0